markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num

blog:
    name: 陈廉政                                                # 博客名称
    description: 个人博客                                         # 博客描述
    title: Image Processing                                              # 网页标题
    url: lianzhengchen.github.io                                        # 博客地址
    qiniu:                                               # 七牛云地址
author:
    name: 陈廉政                                               # 作者名称
    email: LZChenmail@163.com                                              # 邮箱地址
    weibo:                                             # 微博地址
    github: https://github.com/LianzhengChen                                            # GitHub地址
    logo: http://i13.tietuku.com/07a853ba14bc427f.jpg # logo地址
    url: lianzhengchen.github.io                                        # 博客地址
    douban: 
        name:                                            # 豆瓣地址名称
        key:               # 豆瓣API Key

